version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # Match your Lambda runtime (e.g., 3.8, 3.10, 3.11, 3.12)
  build:
    commands:
      # Package the Lambda function code and dependencies
      - echo "Packaging Lambda function..."
      - zip -r package.zip . -x "*.git*" "*.pytest-cache*" "tests/*" "buildspec.yml" "appspec.yml"
  post_build:
    commands:
      - echo "=== Pre-Deployment Setup ==="
      - |
        MAX_RETRIES=10
        RETRY_DELAY=10
        FUNCTION_NAME="lambdafunction"

        echo "Updating function code..."
        UPDATE_OUTPUT=$(aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://package.zip --publish --output json) || {
          echo "Error updating function code"
          exit 1
        }

        echo "Waiting for Lambda update to complete..."
        for i in $(seq 1 $MAX_RETRIES); do
          STATUS=$(aws lambda get-function --function-name $FUNCTION_NAME --query 'Configuration.LastUpdateStatus' --output text)
          if [ "$STATUS" == "Successful" ]; then
            echo "Lambda update successful!"
            break
          elif [ "$STATUS" == "Failed" ]; then
            echo "Lambda update failed!"
            exit 1
          else
            echo "â³ Status: $STATUS (retry $i/$MAX_RETRIES)"
            sleep $RETRY_DELAY
          fi
        done

        if [ "$STATUS" != "Successful" ]; then
          echo "Lambda update did not complete in time."
          exit 1
        fi

        echo "Publishing new version..."
        NEW_VERSION=$(aws lambda publish-version --function-name $FUNCTION_NAME --query 'Version' --output text)
        echo "New Lambda Version: $NEW_VERSION"

        echo "Fetching current version from alias 'prod'..."
        CURRENT_VERSION=$(aws lambda get-alias --function-name $FUNCTION_NAME --name Prod --query 'FunctionVersion' --output text)

        echo "Generating appspec.yml..."
        cat > appspec.yml <<EOF
        version: 0.0
        Resources:
          - myLambdaFunction:
              Type: AWS::Lambda::Function
              Properties:
                Name: $FUNCTION_NAME
                Alias: prod
                CurrentVersion: $CURRENT_VERSION
                TargetVersion: $NEW_VERSION
        EOF

      - echo "Generated appspec.yml:"
      - cat appspec.yml

artifacts:
  files:
    - appspec.yml
  discard-paths: yes