version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # Match your Lambda runtime (e.g., 3.8, 3.10, 3.11, 3.12)
  build:
    commands:
      # Package the Lambda function code and dependencies
      - echo "Packaging Lambda function..."
      - zip package.zip lambdafunctions.py
  post_build:
    commands:
      - echo "=== Pre-Deployment Setup ==="
      # Get current prod alias version for rollback tracking
      - echo "Publishing new Lambda version..."
      - aws lambda update-function-code \
          --function-name my-function \
          --zip-file fileb://package.zip \
          --publish \
          --description "Deployed via CodePipeline $(date)" \
          --query 'Version' --output text)
    
artifacts:
  files:
    - package.zip  # For CodeDeploy or archival
  discard-paths: yes