version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # Match your Lambda runtime (e.g., 3.8, 3.10, 3.11, 3.12)
  build:
    commands:
      # Package the Lambda function code and dependencies
      - echo "Packaging Lambda function..."
      - zip -r package.zip . -x "*.git*" "*.pytest-cache*" "tests/*" "buildspec.yml" "appspec.yml"
  post_build:
    commands:
      - echo "=== Pre-Deployment Setup === "
      # Get current prod alias version for rollback tracking
      - echo "Publishing new Lambda version..."
      - aws lambda update-function-code --function-name lambdafunction --zip-file fileb://package.zip --publish
      - NEW_VERSION=$(aws lambda publish-version --function-name lambdafunction --query 'Version' --output text)
      - echo "Fetching current version from alias 'prod'"
      - CURRENT_VERSION=$(aws lambda get-alias --function-name lambdafunction --name prod --query 'FunctionVersion' --output text)
      - echo "Current Lambda version: $CURRENT_VERSION"
      - echo "New Lambda version: $NEW_VERSION"
      - echo "Generating appspec.yml dynamically"
      - |
        cat > appspec.yml <<EOF
        version: 0.0
        Resources:
          - myLambdaFunction:
              Type: AWS::Lambda::Function
              Properties:
                Name: lambdafunction
                Alias: prod
                CurrentVersion: $CURRENT_VERSION
                TargetVersion: $NEW_VERSION
        EOF

      - echo "Generated appspec.yml:"
      - cat appspec.yml

artifacts:
  files:
    - appspec.yml
  discard-paths: yes